### PR TITLE
Add workflow in actions

### PR DESCRIPTION
**Pull request by recycletechno**
Also added dummy test_simple.py file for pytest to pass. Can delete when tests are ready

### CODE REVIEW

**Comment by Illania** [comment]
@recycletechno which requirements.txt is used? in main we don't have requirements.txt in root folder anymore. please check.

**Comment by Illania** [comment]
looks fine

**Review by Illania — APPROVED** [review]
good work

**Review by alduinsh — APPROVED** [review]
approve, code is ok

**Pull request closed without merging**
